include:
  file: trixie-minbase-ab.yaml

image:
  system_part_size: 2000M # Cage + wayland + chromium + deps
  name: hm-pi-image

layer:
  app: hm-pi
  extra: rpi-splash-screen
  server: hm-pi-server

splash:
  image_path: ${@SRCROOT}/splash.tga

kiosk:
  url: "http://127.0.0.1:3000/"

server:
  repo_url: "https://example.com/your/repo.git"
  project_name: "your-repo"
  # binary_name: "your-binary"
