include:
  file: trixie-minbase-ab.yaml

image:
  system_part_size: 2000M # Cage + wayland + chromium + deps
  name: hm-pi-image

device:
  hostname: mitusa-hm-pi
  user1: mitusa
  user1pass: a1A!b2B@

layer:
  app: hm-pi
  extra: rpi-splash-screen
  server: hm-pi-server
  usbmount: hm-pi-usbmount

splash:
  image_path: ${@SRCROOT}/mitusa-splash.tga
  # Skip image validation checks (not recommended for production)
  skip_image_checks: n

  # Automatically update /boot/firmware/cmdline.txt to enable splash
  update_cmdline: y

kiosk:
  url: "http://127.0.0.1:3000/"

server:
  repo_url: "https://github.com/paul-fornage/hm-pi-htmx.git"
  project_name: "hm-pi-htmx"
  binary_name: "hm-pi-htmx"
